mail.host=smtp.gmail.com
mail.port=587
mail.username=kasandunsathsara01@gmail.com
mail.password=uawcwnmlwijqgiuk
app.mail=info.electrozone@gmail.com
app.name=ElectroZone
app.url=http://localhost:8080/ElectroZone_war_exploded
app.public.url=http://localhost:8080/ElectroZone_war_exploded
payhere.merchant.id=1227897
payhere.merchant.secret=ODExMjQ3MDA3MTkxMDc2OTU0ODQxNzAxNjAwNDEzODU1OTQ3NDgz